# Generated by Django 3.2 on 2021-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
