# Generated by Django 3.2 on 2021-09-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_visit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='day',
        ),
        migrations.AlterField(
            model_name='visit',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
